provider = "gemini"
model = "gemini-2.5-flash-lite"
examples = """
fix(cli/new): prevent double --color arg
feat(cli/new): Pass more options to cargo new
feat(cli): add cargo command
refactor(cli/new): update tests
feat(cli): improves error handling
feat(cli/new): returns error if path exists
feat(cli): improve log message
feat(cli): refactor new command
feat(cli): add InvalidProjectPath error
feat(log): use log macro
chore(justfile): add docs for `check` recipe
fix(cli): remove unused lines
chore(justfile): add check recipe
feat(cli): add dependency notes
feat(cli): refactor error handling
"""
